### ISSUE TITLE
ROS messages passing through Python wrapper

### ISSUE THREAD

**Issue by wxmerkt** [openhumanoids/exotica#100]
As discussed via WhatsApp yesterday, we need a way to pass ROS messages through the Python wrapper to Python-wrapped functions. We are currently investigating the use of serialization/deserialization of messages through buffers, however, they currently segfault at the conversion on the C++ side. Additionally, ``StringIO`` isn't available in Python3 anymore: http://python-future.org/compatible_idioms.html#stringio

**Comment by VladimirIvan** [comment]
The rest of the wrapper works with python3 so I have no objection to making it fully compatible on the pyexotica side.
That said, ROS does not officially support python3 so creating the messages may require extra work.

**Comment by wxmerkt** [comment]
I've now added Python3 compatibility as part of #99
