### ISSUE TITLE
Controlled joint number inconsistency

### ISSUE THREAD

**Issue by VladimirIvan** [openhumanoids/exotica#66]
The number of controlled joints can be obtained using:
```
Scene::getNumJoints()
```
or
```
UnconstrainedEndPoseProblem::N
UnconstrainedTimeIndexedProblem::N
```
The result is the same. Consolidate the calling convention!

**Comment by wxmerkt** [comment]
Is there a distinction between controlled and uncontrolled joints, and if so, how? (i.e. the scene may contain uncontrolled joints that are externally set [grippers], while the problem should only encompass controlled joints)
