### ISSUE TITLE
KinematicTree needs to keep track of links

### ISSUE THREAD

**Issue by wxmerkt** [openhumanoids/exotica#97]
and link names, e.g. for use in explicit collision checking

**Comment by VladimirIvan** [comment]
All segments/links are stored in the `KinematicTree`, in `Tree` as a vector and in `TreeMap` as a map. Their transforms in the world frame (after updating) can be accessed through there as well, e.g.:
```
for(std::shared_ptr<KinematicElement> element : Tree)
{
  KDL::Frame link = element->Frame;
  ...
}
```
Do you need any other interface for this?

**Comment by wxmerkt** [comment]
Not needed anymore, exposed through Scene. A convenience function that retrieves the parent joint of a link may be necessary in the future.
